### ISSUE TITLE
Development env

### ISSUE THREAD

**Issue by piodabro** [MartinLaza/OpenPRO58#1]
Hi,
could you write small doc about Arduino IDE configuration for this project?
I've tried to build it with https://github.com/rogerclarkmelbourne/Arduino_STM32
but there is a lot of differences in libraries.

**Comment by MartinLaza** [comment]
I am working on it right now

**Comment by MartinLaza** [comment]
https://github.com/MartinLaza/OpenPRO58/blob/master/Docs/setup_enviroment.md
