### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by piodabro** [MartinLaza/OpenPRO58#3]
I've set up dev env with your description but cant compile code.
Error is in Audafruit_GFX.h name

In file included from ~\PRO58\src\OpenPRO58\OpenPRO58.ino:14:0:

```
~\AppData\Local\Temp\arduino_build_571405\sketch\ui.h:5:26: fatal error: Adafruit_GFX.h: No such file or directory

 #include <Adafruit_GFX.h>

                          ^

compilation terminated.
```

In libraries for STM this file does not exist, but there is Audafruit_GFX_AS.h
Maybe something changed since you set up your env, but now its not working.

**Comment by piodabro** [comment]
Changing header files from Adafruit_GFX to Adafruit_GFX_AS.h in project files fixes the problem.

**Comment by MartinLaza** [comment]
I will try to do whole packege in one project, so we will have consistent enviroment...

**Comment by piodabro** [comment]
I've done this with making new development environment. Used _AS lib version.
Everything compiles OK.
